name: Publish and test
on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
jobs:
  test:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest] #, ubuntu-latest, macOS-latest]
    steps:
     - name: Checkout
       uses: actions/checkout@v2
       with:
         fetch-depth: 0 # Fetch all history for GitVersionTask to work

     - name: Setup dotnet
       uses: actions/setup-dotnet@v1

     - name: Publish tests
       run: dotnet publish "test/SortingNetworks.Tests/SortingNetworks.Tests.csproj" -o ".deploy/SortingNetworks.Tests" -c "Release"
       env:
         DOTNET_CLI_TELEMETRY_OPTOUT: true

     - name: Run tests
       run: dotnet vstest ".deploy/SortingNetworks.Tests/SortingNetworks.Tests.dll" /Settings:.runsettings